package bot

import (
	"fmt"
	"math"
	"time"

	"ps4-rental/internal/models"
	"ps4-rental/internal/storage"
)

func calculateDisciplineScore(userID string) int {
	r := storage.LoadRatings()
	transactions := r.Transactions[userID]

	if len(transactions) == 0 {
		return 50 // базовый рейтинг для новых клиентов
	}

	window := r.Settings.TransactionsWindow
	if window == 0 {
		window = 5
	}

	recent := transactions
	if len(recent) > window {
		recent = recent[len(recent)-window:]
	}

	var scores []int
	for _, tx := range recent {
		score := 100
		score += tx.Points
		if score < 0 {
			score = 0
		}
		if score > 100 {
			score = 100
		}
		scores = append(scores, score)
	}

	if len(scores) == 0 {
		return 50
	}

	sum := 0
	for _, s := range scores {
		sum += s
	}
	return int(math.Round(float64(sum) / float64(len(scores))))
}

func calculateLoyaltyScore(userID string, user models.User) int {
	r := storage.LoadRatings()
	rules := r.Settings.LoyaltyRules

	score := 0

	// Повторные аренды
	rentals := storage.LoadRentals()
	count := 0
	for _, rental := range rentals {
		if rental.UserID == userID {
			count++
		}
	}

	bonusPerRental := 5
	maxBonus := 30
	if rules != nil {
		if rr, ok := rules["repeat_rentals"].(map[string]interface{}); ok {
			if v, ok := rr["bonus_per_rental"].(float64); ok {
				bonusPerRental = int(v)
			}
			if v, ok := rr["max_bonus"].(float64); ok {
				maxBonus = int(v)
			}
		}
	}

	repeatBonus := count * bonusPerRental
	if repeatBonus > maxBonus {
		repeatBonus = maxBonus
	}
	score += repeatBonus

	// Участие в акциях
	if user.PromotionParticipation {
		promoBonus := 10
		if rules != nil {
			if v, ok := rules["promotion_participation"].(float64); ok {
				promoBonus = int(v)
			}
		}
		score += promoBonus
	}

	// Срок сотрудничества
	if user.JoinedAt != "" {
		joinDate, err := time.Parse(time.RFC3339, user.JoinedAt)
		if err != nil {
			joinDate, _ = time.Parse("2006-01-02T15:04:05", user.JoinedAt)
		}
		if !joinDate.IsZero() {
			days := int(time.Since(joinDate).Hours() / 24)
			tenure12 := 20
			tenure6 := 10
			if rules != nil {
				if tb, ok := rules["tenure_bonus"].(map[string]interface{}); ok {
					if v, ok := tb["12_months"].(float64); ok {
						tenure12 = int(v)
					}
					if v, ok := tb["6_months"].(float64); ok {
						tenure6 = int(v)
					}
				}
			}
			if days >= 365 {
				score += tenure12
			} else if days >= 180 {
				score += tenure6
			}
		}
	}

	score += user.LoyaltyBonus

	if score < 0 {
		score = 0
	}
	if score > 100 {
		score = 100
	}
	return score
}

func calculateUserFinalRating(userID string) *models.UserRatingResult {
	users := storage.LoadUsers()
	user, ok := users[userID]
	if !ok {
		return nil
	}

	r := storage.LoadRatings()
	settings := r.Settings

	discipline := calculateDisciplineScore(userID)
	loyalty := calculateLoyaltyScore(userID, user)

	dw := settings.DisciplineWeight
	lw := settings.LoyaltyWeight
	if dw == 0 {
		dw = 0.6
	}
	if lw == 0 {
		lw = 0.4
	}

	finalScore := int(math.Round(float64(discipline)*dw + float64(loyalty)*lw))
	if finalScore < 0 {
		finalScore = 0
	}
	if finalScore > 100 {
		finalScore = 100
	}

	thresholds := settings.StatusThresholds
	premiumThreshold := 80
	regularThreshold := 50
	if v, ok := thresholds["premium"]; ok {
		premiumThreshold = v
	}
	if v, ok := thresholds["regular"]; ok {
		regularThreshold = v
	}

	status := "risk"
	statusName := "Риск ⚠️"
	if finalScore >= premiumThreshold {
		status = "premium"
		statusName = "Premium ⭐"
	} else if finalScore >= regularThreshold {
		status = "regular"
		statusName = "Обычный 👤"
	}

	return &models.UserRatingResult{
		UserID:       userID,
		FinalScore:   finalScore,
		Discipline:   discipline,
		Loyalty:      loyalty,
		Status:       status,
		StatusName:   statusName,
		CalculatedAt: time.Now(),
	}
}

func addRatingTransaction(userID, txType string, points int, comment string) {
	r := storage.LoadRatings()
	if r.Transactions == nil {
		r.Transactions = make(map[string][]models.RatingTransaction)
	}

	tx := models.RatingTransaction{
		Type:          txType,
		Points:        points,
		Comment:       comment,
		Date:          time.Now().Format(time.RFC3339),
		AutoGenerated: true,
	}
	r.Transactions[userID] = append(r.Transactions[userID], tx)
	_ = storage.SaveRatings(r)
}

func updateRatingOnRentalCompletion(userID string, onTime bool, condition string) {
	if onTime {
		addRatingTransaction(userID, "return_timing", 10, "Возврат вовремя")
	} else {
		addRatingTransaction(userID, "return_timing", -20, "Опоздание при возврате")
	}

	switch condition {
	case "perfect":
		addRatingTransaction(userID, "item_condition", 10, "Отличное состояние")
	case "minor_defects":
		addRatingTransaction(userID, "item_condition", -15, "Незначительные повреждения")
	case "major_defects":
		addRatingTransaction(userID, "item_condition", -30, "Значительные повреждения")
	}

	// Бонус лояльности за повторную аренду
	rentals := storage.LoadRentals()
	completed := 0
	for _, r := range rentals {
		if r.UserID == userID && r.Status == "completed" {
			completed++
		}
	}
	if completed >= 2 {
		addRatingTransaction(userID, "repeat_rental", 5, fmt.Sprintf("Повторная аренда #%d", completed))
	}
}

func getUserStatusBenefits(userID string) map[string]interface{} {
	defaultBenefits := map[string]interface{}{
		"discount_percent":      0,
		"deposit_multiplier":    1.0,
		"priority_support":      false,
		"advance_booking_days":  30,
	}

	rating := calculateUserFinalRating(userID)
	if rating == nil {
		return defaultBenefits
	}

	benefits := map[string]map[string]interface{}{
		"premium": {
			"discount_percent":     10,
			"deposit_multiplier":   0.8,
			"priority_support":     true,
			"advance_booking_days": 45,
		},
		"regular": defaultBenefits,
		"risk": {
			"discount_percent":     0,
			"deposit_multiplier":   1.5,
			"priority_support":     false,
			"advance_booking_days": 7,
		},
	}

	if b, ok := benefits[rating.Status]; ok {
		return b
	}
	return defaultBenefits
}
